version: 1

handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/info.log

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logs/debug.log

  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True
    level: INFO
    markup: True

loggers:
  kedro:
    level: INFO

root:
  handlers: [rich, info_file_handler, debug_file_handler]
  level: DEBUG  