# version: 1

# handlers:
#   info_file_handler:
#     class: logging.handlers.RotatingFileHandler
#     level: INFO
#     filename: logs/info.log

#   debug_file_handler:
#     class: logging.handlers.RotatingFileHandler
#     level: DEBUG
#     filename: logs/debug.log

#   rich:
#     class: kedro.logging.RichHandler
#     rich_tracebacks: True
#     level: INFO
#     markup: True

# loggers:
#   kedro:
#     level: INFO

# root:
#   handlers: [rich, info_file_handler, debug_file_handler]
#   level: DEBUG  

version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    delay: True

loggers:
  kedro:
    level: INFO

root:
  handlers: [console]