day1: Mon
day2: Tue
day3: Wed
day4: Thu
day5: Fri

reward_for_child_staff_role:
  tech: 1
  SBT: 0.8
  TS: 0.6
  SBA: 0.4
  OM: 0.2

constraint_on_off:
  center_hours: True
  staff_child: True
  one_place_per_time: True
  # Lunch adds runtime. Need to simplify. For now, should add heuristically
  lunch: False
  pto: False
  parent_training: False
  team_meeting: False
  nap_time: False
  speech_therapy: False
  arrival_departure: True